project:
  type: website

website:
  title: "Alish Chhetri"
  search:
    location: navbar
    type: textbox
  navbar:
    right:
      - href: index.qmd
      - href: juniorsem.qmd
      - href: seindex.qmd
format:
  html:
    theme: darkly
    css: styles.css
    toc: True