project:
  type: website

website:
  title: "Alish Chhetri"
  site-url: "https://alish-chhetri.netlify.app/"
  navbar:
    left:
      - href: alishindex.qmd
        text: Home
      - href: seindex.qmd
        text: Software Engineering

format:
  html:
    theme: darkly
    css: styles.css
    toc: true



